dataset_path: ./process_data/train_data/dataset.pkl
model_state_dict_path: ./exp/normal/35_4042/checkpoints/model_best.pt
save_dir: ./exp/counterfactual/35_4042/
epochs: 500
lr: 1.e-3
weight_decay: 1.e-4
lam: 15.
hypergraph: 'G_s' # 'G_s' or 'G_i'
logging:
    print_every: 10